# Generated by Django 5.1.4 on 2024-12-18 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_user_fan_user_fans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fan',
            new_name='follow',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fans',
        ),
    ]
