# Generated by Django 5.1.4 on 2024-12-18 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_rename_fan_user_follow_remove_user_fans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
