# Generated by Django 5.1.4 on 2024-12-19 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_user_follow_user_followed_user_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='followed',
            new_name='followers',
        ),
    ]
